/**
 * DEMO data for Kurunduwatta GN division (3-1-39-020, Galle Four Gravets DS, Galle district).
 * Fictional but internally-consistent values for a stakeholder demo of the "Division Information"
 * feature. No real citizen data — matches the strict/required Zod schemas in
 * lib/validators/sections/{health,economic-agriculture,road-infrastructure}.ts.
 * Place names (Temple Road, Main Road/Main Street, Wackwella Road, Watapotha Road, Pahala
 * Kurunduwatta, Play Ground Road, Paddy Field Road) reuse the same fictional GN-division geography
 * established in kurunduwatta-batch-1.ts / kurunduwatta-batch-3.ts.
 */

export const healthData = {
  institutionCounts: {
    govtHospitals: 1,
    primaryHealthcareUnits: 2,
    privateHospitals: 0,
    ayurvedicHospitals: 2,
    specialistServiceCenters: 1,
    mohOfficesOrCommunityHealthCenters: 2,
    privateMedicalLabs: 2,
    traditionalMedicineRegisteredInstitutions: 2,
    animalClinicCenters: 1,
    govtPharmacies: 1,
    privatePharmacies: 3,
  },
  govtHospitalsDirectory: [{ name: "Kurunduwatta Divisional Hospital", type: "divisional" }],
  primaryHealthcareUnitsDirectory: [
    { name: "Kurunduwatta Central Dispensary", type: "Central Dispensary" },
    { name: "Watapotha Maternity Home", type: "Maternity Home" },
  ],
  privateHospitalsDirectory: [],
  ayurvedicInstitutions: [
    { name: "Kurunduwatta Ayurvedic Central Dispensary", address: "Temple Road, Kurunduwatta, Galle" },
    { name: "Shanthi Ayurveda Osu Sala", address: "Wackwella Road, Kurunduwatta, Galle" },
  ],
  specialistServiceCentersDirectory: [{ name: "Kurunduwatta Wellness Center", address: "Main Road, Kurunduwatta, Galle" }],
  mohOfficesDirectory: [
    { name: "MOH Office - Galle", address: "Karapitiya, Galle" },
    { name: "Kurunduwatta Village Health Center", address: "Temple Road, Kurunduwatta, Galle" },
  ],
  traditionalMedicineInstitutionsDirectory: [
    { name: "Kurunduwatta Sinhala Vedakama Center", address: "Watapotha Road, Kurunduwatta, Galle" },
    { name: "Weerasinghe Native Treatment Center", address: "Main Road, Kurunduwatta, Galle" },
  ],
  privateMedicalLabsDirectory: [
    { name: "Suwasetha Medical Laboratory", address: "Main Road, Kurunduwatta, Galle" },
    { name: "Galle Diagnostic Center - Kurunduwatta Branch", address: "Temple Road, Kurunduwatta, Galle" },
  ],
  animalClinicsDirectory: [{ name: "Kurunduwatta Veterinary Clinic", address: "Watapotha Road, Kurunduwatta, Galle" }],
  traditionalPractitioners: [
    { name: "K. A. Sumanadasa Vedamahaththaya", specialty: "Ayurvedic General Physician" },
    { name: "W. M. Padma Kumari", specialty: "Herbal Medicine & Bone-Setting" },
  ],
};

export const economicAgricultureData = {
  landUse: [
    { landType: "forest", extentHectares: 2.5 },
    { landType: "paddy-cultivation", extentHectares: 3 },
    { landType: "abandoned-paddy", extentHectares: 2.5 },
    { landType: "agri-land-tea", extentHectares: 0 },
    { landType: "agri-land-coconut", extentHectares: 15 },
    { landType: "agri-land-rubber", extentHectares: 0 },
    { landType: "cinnamon", extentHectares: 6 },
    { landType: "pepper", extentHectares: 1 },
    { landType: "coffee", extentHectares: 0 },
    { landType: "vegetables", extentHectares: 2 },
    { landType: "fruits", extentHectares: 3 },
    { landType: "tuber-crops", extentHectares: 1.5 },
    { landType: "supplementary-food-crops", extentHectares: 1 },
    { landType: "inland-reservoirs", extentHectares: 0.5 },
    { landType: "roads-sports-homegardens", extentHectares: 20 },
    { landType: "scrub-chena-barren", extentHectares: 5 },
    { landType: "ornamental-nurseries", extentHectares: 0.5 },
    { landType: "plantation-crop-nurseries", extentHectares: 0.3 },
    { landType: "aquaculture-land", extentHectares: 0 },
  ],
  animalHusbandryCounts: [
    { type: "floor-flower-cultivation", count: 3 },
    { type: "greenhouse-cultivation", count: 1 },
    { type: "beekeeping", count: 4 },
  ],
  animalHusbandryDirectory: [
    { type: "beekeeping", name: "H. G. Nimal Perera", address: "Watapotha Road, Kurunduwatta, Galle", phone: "0771234567", marketplace: "local" },
    { type: "beekeeping", name: "D. M. Chandrasena", address: "Temple Road, Kurunduwatta, Galle", phone: "0776543210", marketplace: "local" },
    { type: "floor-flower-cultivation", name: "R. A. Somawathie", address: "Main Road, Kurunduwatta, Galle", phone: "0712345678", marketplace: "national" },
    { type: "greenhouse-cultivation", name: "K. D. Sunil Shantha", address: "Wackwella Road, Kurunduwatta, Galle", phone: "0754567890", marketplace: "local" },
  ],
  specialEconomicActivities: [
    {
      activity: "Cinnamon Peeling & Processing",
      natureOfActivity: "Small-scale cinnamon quill processing for the export trade",
      resourceOrProductUsed: "Cinnamon bark",
    },
    {
      activity: "Coir Fiber Production",
      natureOfActivity: "Household-based coir rope and brush making",
      resourceOrProductUsed: "Coconut husk",
    },
    {
      activity: "Ornamental Fish Breeding",
      natureOfActivity: "Small-scale guppy and goldfish breeding for local sale",
      resourceOrProductUsed: "Freshwater ponds",
    },
  ],
  abandonedPaddyLand: {
    extentAcres: 2.5,
    canBeReactivatedExtent: 1.5,
    reason: "Water scarcity from a silted irrigation channel and younger farmers moving to non-farm work",
    actionPlan: "Proposed channel desilting and small-scale mechanization support to encourage recultivation",
  },
  agriMachinery: [
    { type: "two-wheel-tractor", count: 8 },
    { type: "two-wheel-tractor-rotavator", count: 5 },
    { type: "two-wheel-tractor-mouldboard-plough", count: 3 },
    { type: "four-wheel-tractor", count: 2 },
    { type: "four-wheel-tractor-rotavator", count: 1 },
    { type: "four-wheel-tractor-hook-plough", count: 1 },
    { type: "water-pump", count: 12 },
    { type: "paddy-harvesting-machine", count: 1 },
    { type: "paddy-threshing-machine", count: 2 },
    { type: "combine-harvester", count: 0 },
    { type: "transplanter", count: 0 },
    { type: "power-sprayer", count: 6 },
    { type: "hand-sprayer", count: 15 },
    { type: "weeder", count: 4 },
    { type: "food-drying-machine", count: 1 },
    { type: "floor-flower-media-filling-machine", count: 0 },
    { type: "floor-flower-media-boiling-machine", count: 0 },
    { type: "seedling-planting-machine", count: 0 },
    { type: "paddy-reaping-machine", count: 1 },
    { type: "oil-mill", count: 1 },
    { type: "rubber-mill", count: 0 },
    { type: "paddy-mill", count: 1 },
    { type: "other", count: 0 },
  ],
  forestDamage: [
    { type: "elephant-conflict", present: "no" },
    { type: "wildlife-damage", present: "yes" },
    { type: "peacock-damage", present: "no" },
    { type: "flood-damage", present: "yes" },
    { type: "drought", present: "no" },
    { type: "pest-disease", present: "yes" },
    { type: "other", present: "no" },
  ],
  livestockFarms: [
    {
      name: "Kurunduwatta Dairy Farm",
      address: "Watapotha Road, Kurunduwatta, Galle",
      phone: "0771122334",
      cattle: 12,
      layerChickens: 0,
      broilerChickens: 200,
      goats: 0,
      pigs: 0,
      peacock: 0,
      other: 0,
    },
    {
      name: "Senanayake Poultry Farm",
      address: "Paddy Field Road, Kurunduwatta, Galle",
      phone: "0765544332",
      cattle: 0,
      layerChickens: 500,
      broilerChickens: 0,
      goats: 0,
      pigs: 0,
      peacock: 0,
      other: 0,
    },
    {
      name: "Wijeratne Goat Farm",
      address: "Pahala Kurunduwatta, Galle",
      phone: "0723344556",
      cattle: 0,
      layerChickens: 0,
      broilerChickens: 0,
      goats: 25,
      pigs: 0,
      peacock: 0,
      other: 0,
    },
  ],
  industryCounts: { householdIndustry: 8, under5Employees: 4, over5Employees: 1 },
  industries: [
    { name: "Kurunduwatta Coir Products", productionType: "Coir rope & brush manufacturing", employeeCount: 6, phone: "0771239876", marketplace: "national" },
    { name: "Southern Cinnamon Processors", productionType: "Cinnamon quill peeling & grading", employeeCount: 12, phone: "0762345671", marketplace: "international" },
    { name: "Perera Furniture Works", productionType: "Wooden furniture manufacturing", employeeCount: 4, phone: "0754321098", marketplace: "local" },
  ],
  marineFisheries: { householdCount: 18, fishingPopulation: 65, activeFishermenCount: 22, societyCount: 1 },
  marineFisheriesSocieties: [{ name: "Kurunduwatta Fishermen's Cooperative Society", address: "Wackwella Road, Kurunduwatta, Galle", memberCount: 22 }],
  inlandFisheries: { householdCount: 2, fishingPopulation: 6, activeFishermenCount: 3, societyCount: 0 },
  inlandFisheriesSocieties: [],
  inlandWaterBodies: [
    { name: "Kurunduwatta Wewa", type: "perennial" },
    { name: "Watapotha Seasonal Pond", type: "seasonal" },
  ],
  aquacultureDirectory: [],
  ornamentalFishDirectory: [
    { name: "D. A. Ranjith Kumara", address: "Watapotha Road, Kurunduwatta, Galle", phone: "0778765432" },
    { name: "Guppy World Kurunduwatta", address: "Main Road, Kurunduwatta, Galle", phone: "0711122333" },
  ],
  fishLandingSitePresent: "yes",
  fishLandingSites: [{ name: "Kurunduwatta Fish Landing Site", address: "Wackwella Road, Kurunduwatta, Galle", siteType: "landing-site", waterType: "marine" }],
  iceProductionPresent: "no",
  iceProductionDirectory: [],
  teaEstates: [],
};

export const roadInfrastructureData = {
  publicFacilities: [
    { type: "busStand", present: "yes", name: "Kurunduwatta Bus Stand" },
    { type: "railwayStation", present: "no", name: "" },
    { type: "port", present: "no", name: "" },
    { type: "airport", present: "no", name: "" },
  ],
  roadDevelopmentNeeds: [
    { roadName: "Kurunduwatta Temple Road", roadNumber: "GL/KW/04", lengthMeters: 850, surfaceType: "gravel-soil", maintainingAuthority: "Galle Four Gravets Pradeshiya Sabha" },
    { roadName: "Watapotha Road", roadNumber: "", lengthMeters: 420, surfaceType: "tar", maintainingAuthority: "Galle Four Gravets Pradeshiya Sabha" },
    { roadName: "Wackwella Road Extension", roadNumber: "GL/KW/09", lengthMeters: 600, surfaceType: "carpet", maintainingAuthority: "Road Development Authority" },
  ],
  bridgeRepairs: [
    { name: "Kurunduwatta Ela Culvert", roadNumber: "GL/KW/04", location: "Near Kurunduwatta Junction, Temple Road", maintainingAuthority: "Galle Four Gravets Pradeshiya Sabha" },
    { name: "Watapotha Footbridge", roadNumber: "", location: "Watapotha canal crossing, behind the school", maintainingAuthority: "Galle Four Gravets Pradeshiya Sabha" },
  ],
  newRoadBridgeNeeds: [
    { location: "Between Watapotha Road and Play Ground Road junction", roadNumber: "", justification: "Connecting road needed to shorten travel to the coastal school and clinic" },
    { location: "Paddy Field Road crossing near Kurunduwatta Ela", roadNumber: "", justification: "Existing footbridge is unsafe during monsoon flooding; a proper culvert bridge is needed" },
  ],
  noPublicTransportAreas: [
    { roadName: "Pahala Kurunduwatta Interior Road", roadNumber: "", startPoint: "Pahala Kurunduwatta Junction", endPoint: "Kurunduwatta Ela", distanceKm: 1.2, requiredBeneficiaryCount: 85 },
    { roadName: "Paddy Field Road", roadNumber: "", startPoint: "Wackwella Road turnoff", endPoint: "Fishing community housing", distanceKm: 0.8, requiredBeneficiaryCount: 40 },
  ],
  railwayCrossingGaps: [],
  postOffices: [
    { name: "Kurunduwatta Sub Post Office", type: "sub-post-office" },
    { name: "Watapotha Postal Agency", type: "appointed-post-office" },
  ],
  fuelDistributionStations: [{ name: "Kurunduwatta Filling Station" }],
  solarPowerPlants: [{ name: "Kurunduwatta Community Center Rooftop Solar", scale: "mini" }],
  windPowerPlants: [],
  hydropowerPlants: [],
  financialInstitutions: [
    { name: "Bank of Ceylon - Kurunduwatta Sub Office", type: "govt-bank" },
    { name: "Hatton National Bank - Kurunduwatta Branch", type: "private-bank" },
    { name: "Galle Four Gravets Cooperative Rural Bank - Kurunduwatta", type: "cooperative-rural-bank" },
    { name: "Samurdhi Bank Society - Kurunduwatta", type: "samurdhi-bank" },
  ],
  serviceEstablishments: [
    { category: "retail-shop", count: 14 },
    { category: "eating-house-tea-shop", count: 6 },
    { category: "shoes-textiles", count: 2 },
    { category: "meat-fish-shop", count: 3 },
    { category: "hardware-household-goods", count: 2 },
    { category: "electrical-equipment", count: 1 },
    { category: "general-goods-shop", count: 4 },
    { category: "construction-materials", count: 2 },
    { category: "jewelry", count: 1 },
    { category: "books-stationery", count: 2 },
    { category: "motor-spare-parts", count: 1 },
    { category: "beauty-salon", count: 3 },
    { category: "vehicle-service-center", count: 2 },
    { category: "salon", count: 2 },
    { category: "vehicle-repair", count: 2 },
    { category: "umbrella-bag-shoe-repair", count: 1 },
    { category: "tailoring-shop", count: 3 },
    { category: "funeral-service", count: 1 },
    { category: "mobile-phone-shop", count: 2 },
    { category: "vegetable-shop", count: 5 },
  ],
  industrialEstates: [],
  waterReservoirs: [{ name: "Kurunduwatta Wewa" }],
  publicFacilityCategories: [
    { category: "childrens-park", present: "yes", count: 1, distanceToNearestIfOutsideDivision: "" },
    { category: "library-reading-room", present: "yes", count: 1, distanceToNearestIfOutsideDivision: "" },
    { category: "cinema-hall", present: "no", count: 0, distanceToNearestIfOutsideDivision: "6 km (Galle town)" },
    { category: "auditorium", present: "no", count: 0, distanceToNearestIfOutsideDivision: "4 km (Galle town)" },
    { category: "public-playground", present: "yes", count: 1, distanceToNearestIfOutsideDivision: "" },
    { category: "gym", present: "no", count: 0, distanceToNearestIfOutsideDivision: "3 km (Galle town)" },
    { category: "daycare-center", present: "yes", count: 1, distanceToNearestIfOutsideDivision: "" },
    { category: "cemetery-crematorium", present: "yes", count: 1, distanceToNearestIfOutsideDivision: "" },
    { category: "cultural-center", present: "no", count: 0, distanceToNearestIfOutsideDivision: "5 km (Galle town)" },
    { category: "weekly-fair-market", present: "yes", count: 1, distanceToNearestIfOutsideDivision: "" },
    { category: "community-hall", present: "yes", count: 1, distanceToNearestIfOutsideDivision: "" },
    { category: "vidatha-center", present: "no", count: 0, distanceToNearestIfOutsideDivision: "5 km (Karapitiya, Galle)" },
    { category: "registered-three-wheeler-park", present: "yes", count: 2, distanceToNearestIfOutsideDivision: "" },
  ],
  licensedLiquorShopsPresent: "no",
  licensedLiquorShops: [],
};
